name = "Petit"
uuid = "ffec6195-1160-4285-9170-7fea8d9ba024"
authors = ["jjgomezcadenas <jjgomezcadenas@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
