### A Pluto.jl notebook ###
# v0.20.19

using Markdown
using InteractiveUtils

# This Pluto notebook uses @bind for interactivity. When running this notebook outside of Pluto, the following 'mock version' of @bind gives bound variables a default value (instead of an error).
macro bind(def, element)
    #! format: off
    return quote
        local iv = try Base.loaded_modules[Base.PkgId(Base.UUID("6e696c72-6542-2067-7265-42206c756150"), "AbstractPlutoDingetjes")].Bonds.initial_value catch; b -> missing; end
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : iv(el)
        el
    end
    #! format: on
end

# ╔═╡ 349825ff-7ffe-4fa1-ba26-a772041f0323
begin
	#using Revise
	using PlutoUI
	using CSV
	using DataFrames
	using Plots
	using Printf
	using HDF5
	using Markdown
	using InteractiveUtils
	using Statistics
	using StatsBase
	using Distributions
	using StatsPlots
	#using DataFramesMeta
	
	import Glob
	#using Interpolations
	#using QuadGK
	#using LsqFit
	#using Chain
	#using Unitful 
end

# ╔═╡ 04b446d6-f34f-11ed-2565-0b15d65b6781
PlutoUI.TableOfContents(title="HD5t analysis", indent=true)


# ╔═╡ 940ca858-9258-419b-b6b8-587e7730b5a9
md"""
- Reads "single track files", generated by script batch_track_analysis_mt.jl
- These files contain events with single tracks previously selected. The notebook computes signal and background efficiency calculations.
- This Notice: October-14-2025
"""

# ╔═╡ 871bd8bf-8e4b-40fb-a9c7-fdeb47589c5a
begin
	cmdir=joinpath(ENV["DATA"], "HD5t/precdr")
	pdir =joinpath(ENV["PROJECTS"], "Petit")
end

# ╔═╡ 947c237c-9852-40e9-a83f-c23666db90aa
begin
      using Pkg
      Pkg.activate(pdir)
      Pkg.instantiate()
  end

# ╔═╡ 7504d7aa-a780-4956-99a5-08a7f9a462b2
function ingredients(path::String)
    # this is from the Julia source code (evalfile in base/loading.jl)
    # but with the modification that it returns the module instead of the last object
    name = Symbol(basename(path))
    m = Module(name)
    Core.eval(m,
        Expr(:toplevel,
                :(eval(x) = $(Expr(:core, :eval))($name, x)),
                :(include(x) = $(Expr(:top, :include))($name, x)),
                :(include(mapexpr::Function, x) = $(Expr(:top, :include))(mapexpr, $name, x)),
                :(include($path))))
    m
end

# ╔═╡ c9fc0547-0e73-4629-9909-e59c3d75169d
begin
	jn = ingredients(string(pdir,"/src/Petit.jl"))
end

# ╔═╡ 8290afe2-e5cb-4793-b108-a313f2677119
md"""
## Functions
"""

# ╔═╡ bb52000e-a62c-48df-9b36-b82c0fa92397
 #include("hd5st_functions.jl")

# ╔═╡ 982a3890-7318-4034-b7fd-decafc288362
function voxel_size(dx, dy, p, l)
	sqrt(l)*(dx + dy) /(2.0*sqrt(p))
end

# ╔═╡ d61ec9b7-4922-45de-9b6f-e0a9f4386740
md"""
## Analysis
"""

# ╔═╡ f4e98f28-5f3a-49f5-a053-8ed532e92a60
begin
	vhe = voxel_size(0.75, 1.6, 15.0, 100.0)
	md"""
	- voxel size for 10 % He = $@sprintf("%.1e", vhe) mm
	"""
end

# ╔═╡ 8fc7e228-fb0d-4c6c-ace9-8f6cb057a989
begin
	erex = 12.5 # keV
	rblob = 10.0 # mm
	i = 1
	md"""
	- Energy resolution (keV) = $(erex)
	- rblob (mm) = $(rblob)
	- example track to inspect number = $(i)
	"""
end

# ╔═╡ 22c204c8-9e36-41e0-a0d4-0b86c689739c
begin
	confCut= 0.40
	trklCut = 10.0
	eblb2Max = 1000.0
	md"""
	- Confidence cut = $(confCut)
	- Track Length  cut = $(trklCut)
	- Max energy of Blob 2 = $(eblb2Max)
	"""
end

# ╔═╡ de068020-a64c-43b4-9e78-8ade8a4f6274
begin
	fnBi = "blobsBi.csv"
	fnTl = "blobsTl.csv"
	fnBB = "blobsBB.csv"
	fnXe = "blobsXe.csv"
	fnXe2 = "blobsXe1mm.csv"
	md"""
	- file blobs Bi214 = $(fnBi)
	- file blobs Tl208 = $(fnTl)
	- file blobs bb0nu = $(fnBB)
	- file blobs Xe-137 = $(fnXe)
	- file blobs Xe-137 (1mm voxels)= $(fnXe2)
	"""
end

# ╔═╡ b5f850b0-19ec-4e96-96cc-4c43a91e05f3
begin
	trksBiCopper = jn.Petit.get_bkgnd_tracks(cmdir, isotope="bi214", 
						             bkgnd="copperbkg", 
						             tag="*st3mm*")
	effBiCopper = jn.Petit.Eff(trksBiCopper.n1trk/trksBiCopper.ntot, 1.0, 1.0, 1.0)

	trksBiInner = jn.Petit.get_bkgnd_tracks(cmdir, isotope="bi214", 
						             bkgnd="innerbkg", 
						             tag="*st3mm*")
	effBiInner = jn.Petit.Eff(trksBiInner.n1trk/trksBiInner.ntot, 1.0, 1.0, 1.0)
	
	md"""
	### Bi 214
	#### Copper
	- Total number of events generated = $@sprintf("%.2e", trksBiCopper.ntot)  
	- Total number of events 1 trk  = $(trksBiCopper.n1trk)
	- Selection efficiency: $@sprintf("%.2e", effBiCopper.eff1tr) 

	#### Inner
	- Total number of events generated = $@sprintf("%.2e", trksBiInner.ntot)  
	- Total number of events 1 trk  = $(trksBiInner.n1trk)
	- Selection efficiency: $@sprintf("%.2e", effBiInner.eff1tr) 
	"""
end

# ╔═╡ 9bd589eb-0bbd-4964-b4ba-8a6f8cb7b38b
begin
	trkb214 = vcat(trksBiCopper.tracks, trksBiInner.tracks)
	ntrBi = jn.Petit.NTRKS(length(trkb214), 1, 1, 1) 
	effBi = jn.Petit.Eff(1.0, 1.0, 1.0, 1.0)
	Xbi, Ybi, Zbi =jn.Petit.track_positions(trkb214)
	jn.Petit.histo_xyz(Xbi,Ybi,Zbi,"Bi214")
	
end

# ╔═╡ a60ea1b2-1c4c-4565-ac34-d2580dd016e3
md"""
### Build Tracks: example
"""

# ╔═╡ ce0c0477-0b99-400a-a85e-f8e6cad5e094
let
	xout =jn.Petit.find_track_extremes(trkb214, i=i)
	xresult, xstart_voxel, xend_voxel, xtrack_length, energy_kev = xout
	
	blobs = jn.Petit.energy_in_spheres_around_extremes(trkb214[i], xresult, rblob)
	eb1 = blobs.blob1_energy * 1e+3
	eb2 = blobs.blob2_energy * 1e+3
	nb1 = blobs.blob1_voxel_count
	nb2 = blobs.blob2_voxel_count
	md"""
	#### Find blobs: Example 
	- confidence = $(xresult.confidence)
	- start voxel: x = $(xstart_voxel.x), y = $(xstart_voxel.y), z = $(xstart_voxel.z)
	- end voxel: x = $(xend_voxel.x), y = $(xend_voxel.y), z = $(xend_voxel.z)
	- track length L =$(xtrack_length)
	- energy = $(energy_kev) KeV
	- blob 1 energy = $(round(eb1, digits=1)) keV
	- blob 2 energy = $(round(eb2, digits=1)) keV
	- blob 1 # of voxels = $(nb1)
	- blob 2 # of voxels = $(nb2)
	"""
end

# ╔═╡ 1c202304-d6ca-4dde-a7ac-f5cb2b961b93
jn.Petit.plot_track_blobs(trkb214[i], rblob;
                         markersize_voxels=3.0,
                         show_connections=true,
                         alpha_connections=0.2,
                         alpha_spheres=0.3,
                         sphere_resolution=20)

# ╔═╡ 99258d62-017c-45e2-b9e5-63da00815166
md"""
#### Compute Eblobs for all tracks
"""

# ╔═╡ 4f254ee3-c000-4c49-9f6b-0d7ef947c67d
md"Run blob analysis for Bi214? $(@bind babi CheckBox(default=false))"

# ╔═╡ 403b3c7f-d7c3-4762-8605-5d24fb087415
if babi
	let
		blobsBi = jn.Petit.blob_analysis(trkb214, rblob)
		jn.Petit.write_blobs_csv(blobsBi, fnBi)
	end
end

# ╔═╡ bc7634bf-2d76-4966-95c1-70d3ea97e0ff
blobsBi = CSV.read(fnBi, DataFrame)

# ╔═╡ 067d7785-ce69-4cb6-b783-9fbeab4b9f32
begin
	hEnergyBiTrue, pEnergyBiTrue = jn.Petit.step_hist(collect(blobsBi.energyKeV);
	                                                 nbins = 40,
										             xlim   = (2300.0, 2700.0),
	                                                 xlabel = " E (keV)",
	                                                 ylabel = "Frequency",
	                                                 title=" E true (keV)")
	
	_, pConfidence = jn.Petit.step_hist(collect(blobsBi.confidence);
	                                                 nbins = 20,
										             xlim   = (0.0, 1.0),
	                                                 xlabel = " Confidence ",
	                                                 ylabel = "Frequency",
	                                                 title=" Fit confidence")
	_, pTrkL = jn.Petit.step_hist(collect(blobsBi.trackLength);
	                                                 nbins = 40,
										             #xlim   = (2300.0, 2700.0),
	                                                 xlabel = " Track Length (mm)",
	                                                 ylabel = "Frequency",
	                                                 title=" E true (keV)")
	
	eBi = jn.Petit.smear_histogram(hEnergyBiTrue, erex)
	
	hEnergyBi, pEnergyBi = jn.Petit.step_hist(eBi;
                                              nbins = 40,
                                              xlim   = (2300.0, 2700.0),
                                              xlabel = " E (keV)",
                                              ylabel = "Frequency",
                                              title=" Bi 214 E ")
	plot(pEnergyBiTrue, pEnergyBi, pConfidence, pTrkL )
end

# ╔═╡ c5374971-03ed-4bec-88b6-e636ac400348
md"""
#### Clean up 
- Reject tracks with confidence > $(confCut) 
- Reject tracks with track length < $(trklCut) 
- Reject tracks with track E blob2 > $(eblb2Max) 
"""

# ╔═╡ 898274d5-9add-4b0b-bf04-724bc6e06074
begin
  blobsBiFid = blobsBi[(blobsBi.confidence .> confCut) .& (blobsBi.trackLength .> trklCut) .& (blobsBi.eB2 .< eblb2Max), :]
	
	ntrBi.nfid = size(blobsBiFid)[1]
	effBi.efffid = ntrBi.nfid/ntrBi.ntot
end



# ╔═╡ d4bba489-68d1-4a21-994b-aebbb50fe601
begin
	jn.Petit.histo_b1_b2(blobsBiFid.eB1, blobsBiFid.eB2)
end

# ╔═╡ 8e1206b0-024c-4866-a76c-1f963e2cb303
begin
	jn.Petit.energy_trk_length(eBi, blobsBiFid.trackLength)
end

# ╔═╡ 73cb4e71-d232-4c97-ba8f-27d170823073
begin
	fgbi, pfgbi =jn.Petit.plot_fit_gauss(eBi, "Track Energy", "Counts",
                        30, 2400.0, 2500.0;
                        xgmin=2400.0, xgmax=2500.0, gbins=30)
	plot(pfgbi)
end

# ╔═╡ 4657a7ef-3241-4ea9-81cd-4fb554a37c5b
begin
	effBlbBi = jn.Petit.fom_blobs(blobsBiFid.eB1, 
								  blobsBiFid.eB2,
								  min_cut=200.0,
						          max_cut=600.0,step=25.0)
	
	effEneBi, ffBi = jn.Petit.fom_ecut(eBi; min_cut=2420.0, max_cut=2500.0,step=5.0)
	jn.Petit.eb1_vs_eb2(blobsBiFid.eB1, blobsBiFid.eB2, effBlbBi,eblob_cut=425.0)
end


# ╔═╡ 960a2984-043e-4fab-a981-fe0f8e165e02
effBlbBi

# ╔═╡ 48b32bbf-abbb-480e-9ba0-0df5f0777336
begin
	trksTlCopper = jn.Petit.get_bkgnd_tracks(cmdir, isotope="tl208", 
						             bkgnd="copperbkg", 
						             tag="*st3mm*")
	effTlCopper = jn.Petit.Eff(trksTlCopper.n1trk/trksTlCopper.ntot, 1.0, 1.0, 1.0)

	trksTlInner = jn.Petit.get_bkgnd_tracks(cmdir, isotope="tl208", 
						             bkgnd="innerbkg", 
						             tag="*st3mm*")
	effTlInner = jn.Petit.Eff(trksTlInner.n1trk/trksTlInner.ntot, 1.0, 1.0, 1.0)
	
	md"""
	### Tl 208
	#### Copper
	- Total number of events generated = $@sprintf("%.2e", trksTlCopper.ntot)  
	- Total number of events 1 trk  = $(trksTlCopper.n1trk)
	- Selection efficiency: $@sprintf("%.2e", effTlCopper.eff1tr) 

	#### Inner
	- Total number of events generated = $@sprintf("%.2e", trksTlInner.ntot)  
	- Total number of events 1 trk  = $(trksTlInner.n1trk)
	- Selection efficiency: $@sprintf("%.2e", effTlInner.eff1tr) 
	"""
end

# ╔═╡ 10ed8e9a-e5f4-4652-9f1d-8e59eb605c95
begin
	trktl208 = vcat(trksTlCopper.tracks, trksTlInner.tracks)
	
	ntrTl = jn.Petit.NTRKS(length(trktl208), 1, 1, 1) 
	effTl = jn.Petit.Eff(1.0, 1.0, 1.0, 1.0)
	
	XTl, YTl, ZTl =jn.Petit.track_positions(trktl208)
	jn.Petit.histo_xyz(XTl,YTl,ZTl,"Tl208")
end

# ╔═╡ ba010d8d-f836-4517-b9e3-3f154ce88497
let
	xresult, xstart_voxel, xend_voxel, xtrack_length, energy_kev=jn.Petit.find_track_extremes(trktl208, i=i)
	blobs = jn.Petit.energy_in_spheres_around_extremes(trktl208[i], xresult, rblob)
	eb1 = blobs.blob1_energy * 1e+3
	eb2 = blobs.blob2_energy * 1e+3
	nb1 = blobs.blob1_voxel_count
	nb2 = blobs.blob2_voxel_count
	md"""
	#### Find blobs: Example 
	- confidence = $(xresult.confidence)
	- start voxel: x = $(xstart_voxel.x), y = $(xstart_voxel.y), z = $(xstart_voxel.z)
	- end voxel: x = $(xend_voxel.x), y = $(xend_voxel.y), z = $(xend_voxel.z)
	- track length L =$(xtrack_length)
	- energy = $(energy_kev) KeV
	- blob 1 energy = $(round(eb1, digits=1)) keV
	- blob 2 energy = $(round(eb2, digits=1)) keV
	- blob 1 # of voxels = $(nb1)
	- blob 2 # of voxels = $(nb2)
	"""
end

# ╔═╡ e32cb510-5628-440b-a3ed-a02c0f27005e
jn.Petit.plot_track_blobs(trktl208[i], rblob;
                         markersize_voxels=3.0,
                         show_connections=true,
                         alpha_connections=0.2,
                         alpha_spheres=0.3,
                         sphere_resolution=20)

# ╔═╡ 9cd7ccf0-a4e7-4445-a6b1-78ffa573eb3b
md"Run blob analysis for Bi214? $(@bind batl CheckBox(default=false))"


# ╔═╡ 4bcf1a8b-7101-41e9-bb30-9874275c20a6
if batl
	let
		blobsTl = jn.Petit.blob_analysis(trktl208, rblob)
		jn.Petit.write_blobs_csv(blobsTl, fnTl)
	end
end

# ╔═╡ 37a7d81a-ca8e-4ac5-b2ca-04b261beaddb
blobsTl = CSV.read(fnTl, DataFrame)

# ╔═╡ 01297be8-6234-4bae-91d5-963891b755ef
begin
	hEnergyTlTrue, pEnergyTlTrue = jn.Petit.step_hist(collect(blobsTl.energyKeV);
	                                                 nbins = 40,
										             xlim   = (2300.0, 2700.0),
	                                                 xlabel = " E (keV)",
	                                                 ylabel = "Frequency",
	                                                 title=" E true (keV)")
	
	_, pConfidence2 = jn.Petit.step_hist(collect(blobsTl.confidence);
	                                                 nbins = 20,
										             xlim   = (0.0, 1.0),
	                                                 xlabel = " Confidence ",
	                                                 ylabel = "Frequency",
	                                                 title=" Fit confidence")
	_, pTrkL2 = jn.Petit.step_hist(collect(blobsTl.trackLength);
	                                                 nbins = 40,
										             #xlim   = (2300.0, 2700.0),
	                                                 xlabel = " Track Length (mm)",
	                                                 ylabel = "Frequency",
	                                                 title=" E true (keV)")
	
	eTl = jn.Petit.smear_histogram(hEnergyTlTrue, erex)
	
	hEnergyTl, pEnergyTl = jn.Petit.step_hist(eTl;
                                              nbins = 40,
                                              xlim   = (2300.0, 2700.0),
                                              xlabel = " E (keV)",
                                              ylabel = "Frequency",
                                              title=" Tl 208 E ")
	plot(pEnergyTlTrue, pEnergyTl, pConfidence2, pTrkL2 )
end

# ╔═╡ 9d7572dd-1ebe-426d-a8f9-3dd540775733
begin
  blobsTlFid = blobsTl[(blobsTl.confidence .> confCut) .& (blobsTl.trackLength .> trklCut) .& (blobsTl.eB2 .< eblb2Max), :]
	
	ntrTl.nfid = size(blobsTlFid)[1]
	effTl.efffid = ntrTl.nfid/ntrTl.ntot
end

# ╔═╡ aa3c48c6-3c83-47c3-ac59-ce12de38c371
begin
	jn.Petit.histo_b1_b2(blobsTlFid.eB1, blobsTlFid.eB2)
end

# ╔═╡ 63496eae-e07f-4259-86a7-459de5025613
begin
	jn.Petit.energy_trk_length(eTl, blobsTlFid.trackLength)
end

# ╔═╡ 8c10a242-7411-4973-9fdc-a5e8ce461ee4
begin
	effBlbTl = jn.Petit.fom_blobs(blobsTlFid.eB1, 
										   blobsTlFid.eB2,
										   min_cut=200.0,
						                   max_cut=600.0,step=25.0)
	effEneTl, ffTl = jn.Petit.fom_ecut(eTl; min_cut=2420.0, max_cut=2500.0,step=5.0)
	
	jn.Petit.eb1_vs_eb2(blobsTlFid.eB1, blobsTlFid.eB2, effBlbTl,eblob_cut=425.0)
end

# ╔═╡ 178e3c90-ed84-43e9-b7d8-2282c3758961
begin
	pFomTlEne = jn.Petit.fom_plot(effEneTl, " Efficiency Tl-208: Ecut")
end

# ╔═╡ 2e1c70e9-6ecf-4e97-8705-6342028285aa
md"""
## bb0nu
"""

# ╔═╡ a6e42cf4-1389-497f-90da-1df8297cec74
begin
	trksbb = jn.Petit.get_bb0nu_tracks(cmdir)
	#trksbb.ntot = trksbb.metas[1]["events_processed"]

	effBB = jn.Petit.Eff(trksbb.n1trk/trksbb.ntot, 1.0, 1.0, 1.0)
	
	md"""
	- Total number of bb0nu events generated = $(trksbb.ntot)
	- Total number of bb0nu events 1 trk  = $(trksbb.n1trk)
	- Selection efficiency: $@sprintf("%.2e", effBB.eff1tr) 
	"""
end

# ╔═╡ 759c3202-b6b7-45e7-ab11-75ed778273f7
begin
	trksbb0 = trksbb.tracks
	ntrBB = jn.Petit.NTRKS(length(trksbb0), 1, 1, 1) 
	Xbb, Ybb, Zbb =jn.Petit.track_positions(trksbb0)
	jn.Petit.histo_xyz(Xbb,Ybb,Zbb,"bb0nu")
end

# ╔═╡ f398f371-5271-4af7-965b-73a7027eff0b
let
	xresult, xstart_voxel, xend_voxel, xtrack_length, energy_kev=jn.Petit.find_track_extremes(trksbb0, i=i)
	blobs = jn.Petit.energy_in_spheres_around_extremes(trksbb0[i], xresult, rblob)
	eb1 = blobs.blob1_energy * 1e+3
	eb2 = blobs.blob2_energy * 1e+3
	nb1 = blobs.blob1_voxel_count
	nb2 = blobs.blob2_voxel_count
	md"""
	#### Find blobs: Example 
	- confidence = $(xresult.confidence)
	- start voxel: x = $(xstart_voxel.x), y = $(xstart_voxel.y), z = $(xstart_voxel.z)
	- end voxel: x = $(xend_voxel.x), y = $(xend_voxel.y), z = $(xend_voxel.z)
	- track length L =$(xtrack_length)
	- energy = $(energy_kev) KeV
	- blob 1 energy = $(round(eb1, digits=1)) keV
	- blob 2 energy = $(round(eb2, digits=1)) keV
	- blob 1 # of voxels = $(nb1)
	- blob 2 # of voxels = $(nb2)
	"""
end

# ╔═╡ 00910312-2f5c-49bf-abda-11a6acf86249
jn.Petit.plot_track_blobs(trksbb0[i], rblob;
                         markersize_voxels=3.0,
                         show_connections=true,
                         alpha_connections=0.2,
                         alpha_spheres=0.3,
                         sphere_resolution=20)

# ╔═╡ f7b87c23-dee5-462d-b4b9-b964947b9ca7
md"Run blob analysis for bb0nu? $(@bind babb CheckBox(default=false))"


# ╔═╡ 131e6669-5a26-4d9c-9ef4-911aa779a20e
if babb
	let
		blobsBB = jn.Petit.blob_analysis(trksbb0, rblob)
		jn.Petit.write_blobs_csv(blobsBB, fnBB)
	end
end


# ╔═╡ 18d8eaa0-5467-4123-bfc8-f52f377e7c72
blobsBB = CSV.read(fnBB, DataFrame)

# ╔═╡ ac45ca81-79bc-4631-bf37-c08bbbf6159e
begin
	hEnergyBBTrue, pEnergyBBTrue = jn.Petit.step_hist(collect(blobsBB.energyKeV);
	                                                 nbins = 40,
										             xlim   = (2300.0, 2700.0),
	                                                 xlabel = " E (keV)",
	                                                 ylabel = "Frequency",
	                                                 title=" E true (keV)")
	
	_, pConfidence3 = jn.Petit.step_hist(collect(blobsBB.confidence);
	                                                 nbins = 20,
										             xlim   = (0.0, 1.0),
	                                                 xlabel = " Confidence ",
	                                                 ylabel = "Frequency",
	                                                 title=" Fit confidence")
	_, pTrkL3 = jn.Petit.step_hist(collect(blobsBB.trackLength);
	                                                 nbins = 40,
										             #xlim   = (2300.0, 2700.0),
	                                                 xlabel = " Track Length (mm)",
	                                                 ylabel = "Frequency",
	                                                 title=" E true (keV)")
	
	eBB = jn.Petit.smear_histogram(hEnergyBBTrue, erex)
	
	hEnergyBB, pEnergyBB = jn.Petit.step_hist(eBB;
                                              nbins = 40,
                                              xlim   = (2300.0, 2700.0),
                                              xlabel = " E (keV)",
                                              ylabel = "Frequency",
                                              title=" Bi 214 E ")
	plot(pEnergyBBTrue, pEnergyBB, pConfidence3, pTrkL3 )
end

# ╔═╡ cf3042b0-d5f3-4716-ab25-6ca736b491db
begin
  blobsBBFid = blobsBB[(blobsBB.confidence .> confCut) .& (blobsBB.trackLength .> trklCut) .& (blobsBB.eB2 .< eblb2Max), :]
	
	ntrBB.nfid = size(blobsBBFid)[1]
	effBB.efffid = ntrBB.nfid/ntrBB.ntot
end

# ╔═╡ 794ac8f8-3eee-4a35-96b0-b5dca3615a07
begin
	jn.Petit.histo_b1_b2(blobsBBFid.eB1, blobsBBFid.eB2)
end


# ╔═╡ e571208c-50dd-487d-acb5-e17d5785f92b
begin
	jn.Petit.energy_trk_length(eBB, blobsBBFid.trackLength)
end


# ╔═╡ 6ea54a0d-8b35-47d9-ac29-43b8f1d103db
begin
	fgBB, pfgBB =jn.Petit.plot_fit_gauss(eBB, "Track Energy", "Counts",
                        30, 2400.0, 2500.0;
                        xgmin=2400.0, xgmax=2500.0, gbins=30)
	plot(pfgBB)
end


# ╔═╡ e7ab75e6-33b7-4429-b9a2-b8600856a6fc
begin
	effBlbBB = jn.Petit.fom_blobs(blobsBBFid.eB1, 
								  blobsBBFid.eB2,
								  min_cut=200.0,
						          max_cut=600.0,step=25.0)
	
	effEneBB, ffBB = jn.Petit.fom_ecut(eBB; min_cut=2420.0, 
										  max_cut=2500.0,step=5.0)
	
	jn.Petit.eb1_vs_eb2(blobsBBFid.eB1, blobsBBFid.eB2, effBlbBB,eblob_cut=425.0)
end


# ╔═╡ 04bc7077-564a-470f-8138-c0ecf85d689f
begin
	pFomBBEne = jn.Petit.fom_plot(effEneBB, " Efficiency bb0nu: Ecut")
end

# ╔═╡ 3a233b40-4e22-4a1b-9be5-c0990fc924bd
begin
	fomBiBBx = effEneBB.eff ./(sqrt.(effEneBi.eff))
	fomBiBB = replace(fomBiBBx, NaN => 0.0)
	plot(effEneBB.eblob2, fomBiBB,
          line = :solid,
          linewidth = 2,
          label = nothing,
          color = :blue,
          alpha = 0.5)
end

# ╔═╡ dafbd900-6a41-49bc-8afe-e9e31022ab49
let
	ice = argmax(fomBiBB)
	ecutx = effEneBB.eblob2[ice]
	efbb = effEneBB.eff[ice]
	efbi =effEneBi.eff[ice]
	eftl =effEneTl.eff[ice]
	effBi.effroi = efbi
	effTl.effroi = eftl
	effBB.effroi = efbb
	md"""
	- FOM maximizes at $(ecutx)
	- eff bb0nu = $(efbb)
	- eff bi214 = $(efbi)
	- eff tl208 = $(eftl)
	"""
end

# ╔═╡ 54497681-00c7-4940-9047-23cf1d86b236
begin
	fomBlbBiBBx = effBlbBB.eff ./(sqrt.(effBlbBi.eff))
	fomBlBBiBB = replace(fomBlbBiBBx, NaN => 0.0)
	plot(effBlbBB.eblob2, fomBlBBiBB,
          line = :solid,
          linewidth = 2,
          label = nothing,
          color = :blue,
          alpha = 0.5)
end

# ╔═╡ 50076b02-bd2c-4478-961b-9abee43d82ca
let
	ice = argmax(fomBlBBiBB)
	ecutx = effBlbBB.eblob2[ice]
	efbb = effBlbBB.eff[ice]
	efbi =effBlbBi.eff[ice]
	eftl =effBlbTl.eff[ice]
	effBi.effblb = efbi
	effTl.effblb = eftl
	effBB.effblb = efbb
	md"""
	### Blobs cut
	- FOM maximizes at $(ecutx)
	- eff bb0nu = $(efbb)
	- eff bi214 = $(efbi)
	- eff tl208 = $(eftl)
	"""
end

# ╔═╡ c546afb2-f5cd-4290-ae6d-2805daa2a3fa
begin
  	gout = jn.Petit.gaussian_efficiency_analysis(2458.0,
											   2448.0,12.5, 12.5, 
											   nsteps=20, ff=ffBi)
	zng1, zng2, zp_dists, zeff1, zeff2, zsteps, zp_eff = gout
  	zp_dists  # Show distributions plot
 end

# ╔═╡ 4c76b220-b46a-4ba2-88f0-3bb787b802c2
zp_eff

# ╔═╡ 6a750201-47f6-4fcc-a551-7884c0280bc5
begin
	zeffbb = zeff1[1:end-1]
	zeffbi = zeff2[1:end-1]
	zenergies = zsteps[1:end-1]
	
	zd = Poisson.(ffBi*zeffbi)
	zfom  = zeffbb./std.(zd) 
	plot(zenergies, zfom,
                marker=:circle, markersize=5, lw=2,
                label="FOM ",
                xlabel="Step", ylabel="fom",
                title="FOM Curve",
                legend=:topright, ylim=(0, 1.5))
end

# ╔═╡ 56917df0-2e21-44c4-a7b7-3619a8661ab5
let
	ice = argmax(zfom)
	ecutx = zenergies[ice]
	efbb = zeffbb[ice]
	efbi =zeffbi[ice]
	md"""
	- Gaussian FOM maximizes at $(ecutx)
	- eff bb0nu = $(efbb)
	- eff bi214 = $(efbi)
	"""
end

# ╔═╡ ffb9d0d1-bca6-4b9a-87a7-e8c6280488fa
md"""
## Signal and background efficiency
"""

# ╔═╡ 4eeabfad-fb46-4d90-a586-aaf712c9eb47
let
	jn.Petit.copy_eff!(effBiCopper , effBi)
	jn.Petit.copy_eff!(effBiInner , effBi)
	jn.Petit.copy_eff!(effTlCopper , effTl)
	jn.Petit.copy_eff!(effTlInner , effTl)
	#println("effBiCopper ->",effBiCopper)
	#println("effBiInner ->",effBiInner)
	#println("effTlCopper ->",effTlCopper)
	#println("effTlInner ->",effTlInner)

	eff_bi_copper = jn.Petit.total_eff(effBiCopper)
	eff_bi_inner = jn.Petit.total_eff(effBiInner)
	eff_tl_copper = jn.Petit.total_eff(effTlCopper)
	eff_tl_inner = jn.Petit.total_eff(effTlInner)
	eff_bb0 = jn.Petit.total_eff(effBB)
	md"""
	#### Efficiencies for signal and background:
	- signal = $@sprintf("%.2e", eff_bb0)
	- bi from copper = $@sprintf("%.2e", eff_bi_copper)
	- bi from inner = $@sprintf("%.2e", eff_bi_inner)
	- tl from copper = $@sprintf("%.2e", eff_tl_copper)
	- tl from inner = $@sprintf("%.2e", eff_tl_inner)
	"""
end

# ╔═╡ 0397d23d-6c74-484b-9c8a-3989bab21239
md"""
## Xe-137
"""

# ╔═╡ d7729d46-79ac-48c2-948a-41c91f78e2e3
begin
	trksxe =  jn.Petit.get_xe137_tracks(cmdir)
	effXe = jn.Petit.Eff(trksxe.n1trk/trksxe.ntot, 1.0, 1.0, 1.0)
	
	md"""
	- Total number of Xe-137 events generated = $(trksxe.ntot)
	- Total number of Xe-137 events 1 trk  = $(trksxe.n1trk)
	- Selection efficiency: $@sprintf("%.2e", effXe.eff1tr) 
	"""
end

# ╔═╡ ac25b86e-97b3-4d54-b71a-a68a79a90995
begin
	trksxe1e = trksxe.tracks
	ntrXe = jn.Petit.NTRKS(length(trksxe1e), 1, 1, 1) 
	Xxe, Yxe, Zxe =jn.Petit.track_positions(trksxe1e)
	jn.Petit.histo_xyz(Xxe,Yxe,Zxe,"Xe-137")
end

# ╔═╡ 6ec7bab6-27c1-450d-a346-9abe523f1ca7
let
	xresult, xstart_voxel, xend_voxel, xtrack_length, energy_kev=jn.Petit.find_track_extremes(trksxe1e, i=i)
	blobs = jn.Petit.energy_in_spheres_around_extremes(trksxe1e[i], xresult, rblob)
	eb1 = blobs.blob1_energy * 1e+3
	eb2 = blobs.blob2_energy * 1e+3
	nb1 = blobs.blob1_voxel_count
	nb2 = blobs.blob2_voxel_count
	md"""
	#### Find blobs: Example 
	- confidence = $(xresult.confidence)
	- start voxel: x = $(xstart_voxel.x), y = $(xstart_voxel.y), z = $(xstart_voxel.z)
	- end voxel: x = $(xend_voxel.x), y = $(xend_voxel.y), z = $(xend_voxel.z)
	- track length L =$(xtrack_length)
	- energy = $(energy_kev) KeV
	- blob 1 energy = $(round(eb1, digits=1)) keV
	- blob 2 energy = $(round(eb2, digits=1)) keV
	- blob 1 # of voxels = $(nb1)
	- blob 2 # of voxels = $(nb2)
	"""
end

# ╔═╡ 75547508-ba93-4df5-af81-6026f88499a5
jn.Petit.plot_track_blobs(trksxe1e[i], rblob;
                         markersize_voxels=3.0,
                         show_connections=true,
                         alpha_connections=0.2,
                         alpha_spheres=0.3,
                         sphere_resolution=20)

# ╔═╡ 2f87d310-8d44-4649-9dfb-440e160a24f4
md"Run blob analysis for xe137? $(@bind baxe CheckBox(default=false))"


# ╔═╡ 93f37121-c331-4e84-80ac-66c4c6e2aef6
if baxe
	let
		blobsXe = jn.Petit.blob_analysis(trksxe1e, rblob)
		jn.Petit.write_blobs_csv(blobsXe, fnXe)
	end
end


# ╔═╡ 10a4a567-6337-418b-a70e-97647af0177b
blobsXe = CSV.read(fnXe, DataFrame)

# ╔═╡ f333b7c7-bebb-47da-bbfc-b350f0f34a0d
begin
	hEnergyXeTrue, pEnergyXeTrue = jn.Petit.step_hist(collect(blobsXe.energyKeV);
	                                                 nbins = 40,
										             xlim   = (2300.0, 2700.0),
	                                                 xlabel = " E (keV)",
	                                                 ylabel = "Frequency",
	                                                 title=" E true (keV)")
	
	_, pConfidence4 = jn.Petit.step_hist(collect(blobsXe.confidence);
	                                                 nbins = 20,
										             xlim   = (0.0, 1.0),
	                                                 xlabel = " Confidence ",
	                                                 ylabel = "Frequency",
	                                                 title=" Fit confidence")
	_, pTrkL4 = jn.Petit.step_hist(collect(blobsXe.trackLength);
	                                                 nbins = 40,
										             #xlim   = (2300.0, 2700.0),
	                                                 xlabel = " Track Length (mm)",
	                                                 ylabel = "Frequency",
	                                                 title=" E true (keV)")
	
	eXe = jn.Petit.smear_histogram(hEnergyXeTrue, erex)
	
	hEnergyXe, pEnergyXe = jn.Petit.step_hist(eXe;
                                              nbins = 40,
                                              xlim   = (2300.0, 2700.0),
                                              xlabel = " E (keV)",
                                              ylabel = "Frequency",
                                              title=" Xe-136E ")
	plot(pEnergyXeTrue, pEnergyXe, pConfidence4, pTrkL4 )
end

# ╔═╡ d995912c-5e3d-46da-a19b-730498af7ff5
begin
  blobsXeFid = blobsXe[(blobsXe.confidence .> confCut) .& (blobsXe.trackLength .> trklCut) .& (blobsXe.eB2 .< eblb2Max), :]
	
	ntrXe.nfid = size(blobsXeFid)[1]
	effXe.efffid = ntrXe.nfid/ntrXe.ntot
end

# ╔═╡ f35f3201-6180-418d-aa4a-b495f4a9de09
begin
	jn.Petit.histo_b1_b2(blobsXeFid.eB1, blobsXeFid.eB2)
end


# ╔═╡ 64fa7f0f-5515-4990-839b-e92d5edf4f44
begin
	jn.Petit.energy_trk_length(eXe, blobsXeFid.trackLength)
end

# ╔═╡ 9240273d-a92e-403e-a582-a7cb4789be60
begin
	effBlbXe = jn.Petit.fom_blobs(blobsXeFid.eB1, 
								  blobsXeFid.eB2,
								  min_cut=200.0,
						          max_cut=600.0,step=25.0)
	
	effEneXe, ffXe = jn.Petit.fom_ecut(eXe; min_cut=2420.0,
										   max_cut=2500.0,step=5.0)
	jn.Petit.eb1_vs_eb2(blobsXeFid.eB1, blobsXeFid.eB2, effBlbXe,eblob_cut=425.0)
end

# ╔═╡ 48577121-4f6b-494f-8ae4-d8db338089fa
begin
	fomBlbXeBBx = effBlbBB.eff ./(sqrt.(effBlbXe.eff))
	fomBlBXeBB = replace(fomBlbXeBBx, NaN => 0.0)
	plot(effBlbBB.eblob2, fomBlBXeBB,
          line = :solid,
          linewidth = 2,
          label = nothing,
          color = :blue,
          alpha = 0.5)
end

# ╔═╡ 2837e158-e36c-49cd-9eaf-7ffd09f064b8
let
	ice = argmax(fomBlBXeBB) +1
	ecutx = effBlbBB.eblob2[ice]
	efbb = effBlbBB.eff[ice]
	efbi =effBlbBi.eff[ice]
	eftl =effBlbTl.eff[ice]
	efxe =effBlbXe.eff[ice]
	effBi.effblb = efbi
	effTl.effblb = eftl
	effBB.effblb = efbb
	effXe.effblb = efxe
	md"""
	### Blobs cut
	- FOM maximizes at $(ecutx)
	- eff bb0nu = $(efbb)
	- eff bi214 = $(efbi)
	- eff tl208 = $(eftl)
	- eff xe-137 = $(efxe)
	"""
end

# ╔═╡ d7648894-3e02-47ca-af42-a288190f699d
let
	jn.Petit.copy_eff!(effBiCopper , effBi)
	jn.Petit.copy_eff!(effBiInner , effBi)
	jn.Petit.copy_eff!(effTlCopper , effTl)
	jn.Petit.copy_eff!(effTlInner , effTl)
	

	eff_bi_copper = jn.Petit.total_eff(effBiCopper)
	eff_bi_inner = jn.Petit.total_eff(effBiInner)
	eff_tl_copper = jn.Petit.total_eff(effTlCopper)
	eff_tl_inner = jn.Petit.total_eff(effTlInner)
	eff_xe = jn.Petit.total_eff(effXe)
	eff_bb0 = jn.Petit.total_eff(effBB)

	df = DataFrame(
	      signal = eff_bb0,
	      Xe137 = eff_xe,
	      bi_copper = eff_bi_copper,
	      bi_inner = eff_bi_inner,
	      tl_copper = eff_tl_copper,
	      tl_inner = eff_tl_inner
	  )
	
	  CSV.write("efficiencies.csv", df)
	
	md"""
	#### Efficiencies for signal and background:
	- signal = $@sprintf("%.2e", eff_bb0)
	- Xe137 = $@sprintf("%.2e", eff_xe)
	- bi from copper = $@sprintf("%.2e", eff_bi_copper)
	- bi from inner = $@sprintf("%.2e", eff_bi_inner)
	- tl from copper = $@sprintf("%.2e", eff_tl_copper)
	- tl from inner = $@sprintf("%.2e", eff_tl_inner)
	"""
end

# ╔═╡ c3fd5ca5-a8a4-4a38-a314-6d6ca7550784
md"""
## Xe-137, voxels 1mm 
"""

# ╔═╡ 1201f9f7-1cff-4626-8ce4-cd07a830a35f
begin
	trksxev1 =  jn.Petit.get_xe137_tracks(cmdir, xedir="xe137v1mm", 
										  tag="*st1mm*")
	effXev1 = jn.Petit.Eff(trksxev1.n1trk/trksxev1.ntot, 1.0, 1.0, 1.0)
	
	md"""
	- Total number of Xe-137 events generated = $(trksxev1.ntot)
	- Total number of Xe-137 events 1 trk  = $(trksxev1.n1trk)
	- Selection efficiency: $@sprintf("%.2e", effXev1.eff1tr) 
	"""
end

# ╔═╡ cecc54f1-529b-456e-a3c4-1245f96f6102
begin
	trksxe1ev1 = trksxev1.tracks
	ntrXev1 = jn.Petit.NTRKS(length(trksxe1ev1), 1, 1, 1) 
	Xxe2, Yxe2, Zxe2 =jn.Petit.track_positions(trksxe1ev1)
	jn.Petit.histo_xyz(Xxe2,Yxe2,Zxe2,"Xe-137")
end


# ╔═╡ 2c07fc77-c307-4e1c-89da-20b7e888ed93
let
	xresult, xstart_voxel, xend_voxel, xtrack_length, energy_kev=jn.Petit.find_track_extremes(trksxe1ev1, i=i)
	blobs = jn.Petit.energy_in_spheres_around_extremes(trksxe1ev1[i], xresult, rblob)
	eb1 = blobs.blob1_energy * 1e+3
	eb2 = blobs.blob2_energy * 1e+3
	nb1 = blobs.blob1_voxel_count
	nb2 = blobs.blob2_voxel_count
	md"""
	#### Find blobs: Example 
	- confidence = $(xresult.confidence)
	- start voxel: x = $(xstart_voxel.x), y = $(xstart_voxel.y), z = $(xstart_voxel.z)
	- end voxel: x = $(xend_voxel.x), y = $(xend_voxel.y), z = $(xend_voxel.z)
	- track length L =$(xtrack_length)
	- energy = $(energy_kev) KeV
	- blob 1 energy = $(round(eb1, digits=1)) keV
	- blob 2 energy = $(round(eb2, digits=1)) keV
	- blob 1 # of voxels = $(nb1)
	- blob 2 # of voxels = $(nb2)
	"""
end


# ╔═╡ e31d09c9-692c-4e42-aaad-740bb1dd8046
jn.Petit.plot_track_blobs(trksxe1ev1[i], rblob;
                         markersize_voxels=3.0,
                         show_connections=true,
                         alpha_connections=0.2,
                         alpha_spheres=0.3,
                         sphere_resolution=20)


# ╔═╡ 56132a5d-d190-488d-91fd-3a219e955715
md"Run blob analysis for xe137? $(@bind baxe2 CheckBox(default=false))"


# ╔═╡ d3058953-4c3e-4d0d-b1fc-9c681cdcc817
#if baxe2
#	let
#		blobsXev1 = jn.Petit.blob_analysis(trksxe1ev1, rblob, nevents=10)
#		jn.Petit.write_blobs_csv(blobsXev1, fnXe2)

#	end
#end

# ╔═╡ 3af762e0-6920-4ff6-9c46-06512300c051
md"""
- Xe137 with voxels 1 mm and r = 5 mm
"""

# ╔═╡ 83a0689f-1639-4f16-94cc-dc22df2aaf9f
blobsXev1 = jn.Petit.merge_csv_files("xe_vx_1mm_r_5mm")

# ╔═╡ 611a4da8-f77e-4ece-9509-25622e1e78b5
begin
	hEnergyXeTruev1, pEnergyXeTruev1 = jn.Petit.step_hist(collect(blobsXev1.energyKeV);
	                                                 nbins = 40,
										             xlim   = (2300.0, 2700.0),
	                                                 xlabel = " E (keV)",
	                                                 ylabel = "Frequency",
	                                                 title=" E true (keV)")
	
	_, pConfidence5 = jn.Petit.step_hist(collect(blobsXev1.confidence);
	                                                 nbins = 20,
										             xlim   = (0.0, 1.0),
	                                                 xlabel = " Confidence ",
	                                                 ylabel = "Frequency",
	                                                 title=" Fit confidence")
	_, pTrkL5 = jn.Petit.step_hist(collect(blobsXev1.trackLength);
	                                                 nbins = 40,
										             #xlim   = (2300.0, 2700.0),
	                                                 xlabel = " Track Length (mm)",
	                                                 ylabel = "Frequency",
	                                                 title=" E true (keV)")
	
	eXev1 = jn.Petit.smear_histogram(hEnergyXeTruev1, erex)
	
	hEnergyXev1, pEnergyXev1 = jn.Petit.step_hist(eXev1;
                                              nbins = 40,
                                              xlim   = (2300.0, 2700.0),
                                              xlabel = " E (keV)",
                                              ylabel = "Frequency",
                                              title=" Xe-136E ")
	plot(pEnergyXeTruev1, pEnergyXev1, pConfidence5, pTrkL5 )
end

# ╔═╡ a7ec3901-5982-4911-b7b4-30870e891b5c
begin
  blobsXeFidv1 = blobsXev1[(blobsXev1.confidence .> confCut) .& (blobsXev1.trackLength .> trklCut) .& (blobsXev1.eB2 .< eblb2Max), :]
	
	ntrXev1.nfid = size(blobsXeFidv1)[1]
	effXev1.efffid = ntrXev1.nfid/ntrXe.ntot
end


# ╔═╡ 2d2ba724-3073-41aa-aab1-89e74e02e4f0
begin
	jn.Petit.histo_b1_b2(blobsXeFidv1.eB1, blobsXeFidv1.eB2)
end


# ╔═╡ da77f748-0896-43a5-8fb0-93d3cc887bd1
begin
	jn.Petit.energy_trk_length(eXev1, blobsXeFidv1.trackLength)
end


# ╔═╡ 5520c3fe-04e7-4028-a21e-4e5d3cbd4a11
begin
	effBlbXev1 = jn.Petit.fom_blobs(blobsXeFidv1.eB1, 
								  blobsXeFidv1.eB2,
								  min_cut=100.0,
						          max_cut=500.0,step=25.0)
	
	effEneXev1, ffXev1 = jn.Petit.fom_ecut(eXev1; min_cut=2420.0,
										   max_cut=2500.0,step=5.0)
	jn.Petit.eb1_vs_eb2(blobsXeFidv1.eB1, blobsXeFidv1.eB2, 
							effBlbXev1,eblob_cut=425.0)
end

# ╔═╡ d86d7f62-100d-45f1-a71e-45ed79f97afb
effBlbXev1

# ╔═╡ b86272a2-0675-4727-a002-4749e82a15b5
md"""
- bb0nu with voxels 1 mm and r = 5 mm
"""

# ╔═╡ c65dadd6-5587-4c8a-930e-cd2bf9b25604
blobsBBv1R5 = jn.Petit.merge_csv_files("bb0nu_vx_1mm_r_5mm")

# ╔═╡ 0631ecea-6fd8-44d9-9f5b-7a885126fca2
begin
	jn.Petit.histo_b1_b2(blobsBBv1R5.eB1, blobsBBv1R5.eB2)
end

# ╔═╡ 1366db75-3e89-4d71-a398-b4d06005a1bd
begin
	effBlbBBv1R5 = jn.Petit.fom_blobs(blobsBBv1R5.eB1, 
								  blobsBBv1R5.eB2,
								  min_cut=100.0,
						          max_cut=500.0,step=25.0)
	
	jn.Petit.eb1_vs_eb2(blobsBBv1R5.eB1, blobsBBv1R5.eB2, 
							effBlbBBv1R5,eblob_cut=425.0)
end

# ╔═╡ 508f5350-f539-44a3-8b6a-94793083e6b7
effBlbBBv1R5

# ╔═╡ f15ad4b6-873a-4ce3-8321-5a38e9704df2
md"""
### Blob efficiencies
"""

# ╔═╡ ffc1b36a-7df4-48f6-8fff-5095d50d6039
let
	results = [effBlbBi, effBlbTl, effBlbXe, effBlbXev1]
	labels = ["Bi-214", "Tl-208", "1e", "1ev1"]
	jn.Petit.fom_plots(results, labels)
end

# ╔═╡ d0f9e26b-2a3c-42a4-a826-7c8694f5d470
md"""
# Functions
"""

# ╔═╡ beb867b5-711f-47ba-b6d1-c3a6e63dd6f1
function histogram_alphas(df)
	
	h_x, p_x = jn.Petit.step_hist(df.x;
         nbins = 50,
         xlim   = (-2000.0, 2000.0),
         xlabel = "X (mm)",
         ylabel = "Frequency",
         title=" X")

	h_y, p_y = jn.Petit.step_hist(df.y;
         nbins = 50,
         xlim   = (-2000.0, 2000.0),
         xlabel = "Y (mm)",
         ylabel = "Frequency",
         title=" Y")

	h_z, p_z = jn.Petit.step_hist(df.z;
         nbins = 50,
         xlim   = (-2000.0, 2000.0),
         xlabel = "Z (mm)",
         ylabel = "Frequency",
         title=" Z ")

	h_e, p_e = jn.Petit.step_hist(1e+3*df.energy;
         nbins = 50,
         xlim   = (0.0, 8000.0),
         xlabel = "energy (V)",
         ylabel = "Frequency",
         title=" E (keV) ")

	plot(p_x, p_y, p_z, p_e)
end

# ╔═╡ 33efdcc5-cc1d-48f4-81af-b5f65bb348f7
function histogram_stats(hitsdf)
	h_id, p_id = jn.Petit.step_hist(hitsdf.event_id;
         nbins = 50,
         xlim   = (0.0, 10000.0),
         xlabel = "event number",
         ylabel = "Frequency",
         title=" Events")
	
	nhits = jn.Petit.hits_per_all_events(hitsdf)
	h_nhits, p_nhits = jn.Petit.step_hist(nhits;
         nbins = 50,
         xlim   = (0.0, 500.0),
         xlabel = "number of hits per track",
         ylabel = "Frequency",
         title=" Hits per track")

	h_x, p_x = jn.Petit.step_hist(hitsdf.x;
         nbins = 50,
         xlim   = (-2000.0, 2000.0),
         xlabel = "X (mm)",
         ylabel = "Frequency",
         title=" X")

	h_y, p_y = jn.Petit.step_hist(hitsdf.y;
         nbins = 50,
         xlim   = (-2000.0, 2000.0),
         xlabel = "Y (mm)",
         ylabel = "Frequency",
         title=" Y")

	h_z, p_z = jn.Petit.step_hist(hitsdf.z;
         nbins = 50,
         xlim   = (-2000.0, 2000.0),
         xlabel = "Z (mm)",
         ylabel = "Frequency",
         title=" Z ")

	plot(p_nhits, p_x, p_y, p_z)
end

# ╔═╡ 6fc13d23-cb44-40a6-a52d-32b81855d6a0
function histogram_voxel_energy(df; emx=200.0, title="Voxel energy")
	h_vxe, p_vxe = jn.Petit.step_hist(1e+3*df.energy;
         nbins = 50,
         xlim   = (0.0, emx),
         xlabel = "Voxel energy (keV)",
         ylabel = "Frequency",
         title=title)
	plot(p_vxe)
end

# ╔═╡ 2d4732eb-47b0-498b-b0ff-c9dcf3951ecd
function histogram_distances(df; dmx=100.0, dcmx=20.0)
	vd = jn.Petit.voxel_distances(df)
	vcd = jn.Petit.voxel_closest_distance(df)
	_, p_vd = jn.Petit.step_hist(vd;
         nbins = 50,
         xlim   = (0.0, dmx),
         xlabel = "voxel distance (mm)",
         ylabel = "Frequency",
         title=" Voxel Distance ")
	_, p_vcd = jn.Petit.step_hist(vcd;
         nbins = 50,
         xlim   = (0.0, dcmx),
         xlabel = "voxel closest distance (mm)",
         ylabel = "Frequency",
         title=" Voxel Closest Distance ")
	
	plot(p_vd, p_vcd)
end

# ╔═╡ 769f772d-2695-468f-93a0-7655b5d08f10
function histogram_energies_trks(results)
	
	_, p_t1 = jn.Petit.step_hist(results.single_track.energy;
         nbins = 50,
         xlim   = (0.0, 2700.0),
         xlabel = " E (keV)",
         ylabel = "Frequency",
         title=" E one track ")
	_, p_t2 = jn.Petit.step_hist(results.two_track_primary.energy;
         nbins = 50,
         xlim   = (0.0, 2700.0),
         xlabel = " E (keV)",
         ylabel = "Frequency",
         title=" E two tracks ")
	_, p_t2s = jn.Petit.step_hist(results.two_track_secondary.energy;
         nbins = 50,
         xlim   = (0.0, 250.0),
         xlabel = " E (keV)",
         ylabel = "Frequency",
         title=" E secondaries 2t ")
	_, p_t3s = jn.Petit.step_hist(results.three_track_secondary.energy;
         nbins = 50,
         xlim   = (0.0, 250.0),
         xlabel = " E (keV)",
         ylabel = "Frequency",
         title=" E secondaries 3 track ")
	
	plot(p_t1, p_t2, p_t2s, p_t3s)
end

# ╔═╡ 4bb62775-b172-4537-9087-c37cf9ea97f4
function plot_true_hits2(ghdf::GroupedDataFrame, index::Int; nbins=100)
    df = get_event(ghdf, index)
	plot_hits_evt(df; nbins)
end

# ╔═╡ 46d3b837-c9df-4e04-98ae-611054c9ad6d
function get_group_contents(filename::String; path::String = "/")
    h5open(filename, "r") do file
        if !haskey(file, path)
            error("Path $path not found in HDF5 file.")
        end
        group = file[path]
        return Dict(name => typeof(group[name]) for name in keys(group))
    end
end

# ╔═╡ a4d68f10-b2f3-4b48-b3d0-2baac6f93ca1
function get_subgroups(filename::String, path::String = "/")
    h5open(filename, "r") do file
        if !haskey(file, path)
            error("Path $path not found in HDF5 file.")
        end
        group = file[path]
        return [name for name in keys(group) if group[name] isa HDF5.Group]
    end
end

# ╔═╡ bbc7767d-2ab4-40ff-ad2a-e1f81b6ad368
function inspect_mc(filename::String)
    h5open(filename, "r") do fid
        dset = fid["MC"]
        println("Type: ", typeof(dset))
        data = read(dset)
        println("Read type: ", typeof(data))
        println("First element: ", data[1])
        return data
    end
end

# ╔═╡ Cell order:
# ╠═947c237c-9852-40e9-a83f-c23666db90aa
# ╠═04b446d6-f34f-11ed-2565-0b15d65b6781
# ╠═940ca858-9258-419b-b6b8-587e7730b5a9
# ╠═871bd8bf-8e4b-40fb-a9c7-fdeb47589c5a
# ╠═349825ff-7ffe-4fa1-ba26-a772041f0323
# ╠═7504d7aa-a780-4956-99a5-08a7f9a462b2
# ╠═c9fc0547-0e73-4629-9909-e59c3d75169d
# ╠═8290afe2-e5cb-4793-b108-a313f2677119
# ╠═bb52000e-a62c-48df-9b36-b82c0fa92397
# ╠═982a3890-7318-4034-b7fd-decafc288362
# ╠═d61ec9b7-4922-45de-9b6f-e0a9f4386740
# ╠═f4e98f28-5f3a-49f5-a053-8ed532e92a60
# ╠═8fc7e228-fb0d-4c6c-ace9-8f6cb057a989
# ╠═22c204c8-9e36-41e0-a0d4-0b86c689739c
# ╠═de068020-a64c-43b4-9e78-8ade8a4f6274
# ╠═b5f850b0-19ec-4e96-96cc-4c43a91e05f3
# ╠═9bd589eb-0bbd-4964-b4ba-8a6f8cb7b38b
# ╠═a60ea1b2-1c4c-4565-ac34-d2580dd016e3
# ╠═ce0c0477-0b99-400a-a85e-f8e6cad5e094
# ╠═1c202304-d6ca-4dde-a7ac-f5cb2b961b93
# ╠═99258d62-017c-45e2-b9e5-63da00815166
# ╠═4f254ee3-c000-4c49-9f6b-0d7ef947c67d
# ╠═403b3c7f-d7c3-4762-8605-5d24fb087415
# ╠═bc7634bf-2d76-4966-95c1-70d3ea97e0ff
# ╠═067d7785-ce69-4cb6-b783-9fbeab4b9f32
# ╠═c5374971-03ed-4bec-88b6-e636ac400348
# ╠═898274d5-9add-4b0b-bf04-724bc6e06074
# ╠═d4bba489-68d1-4a21-994b-aebbb50fe601
# ╠═8e1206b0-024c-4866-a76c-1f963e2cb303
# ╠═73cb4e71-d232-4c97-ba8f-27d170823073
# ╠═4657a7ef-3241-4ea9-81cd-4fb554a37c5b
# ╠═960a2984-043e-4fab-a981-fe0f8e165e02
# ╠═48b32bbf-abbb-480e-9ba0-0df5f0777336
# ╠═10ed8e9a-e5f4-4652-9f1d-8e59eb605c95
# ╠═ba010d8d-f836-4517-b9e3-3f154ce88497
# ╠═e32cb510-5628-440b-a3ed-a02c0f27005e
# ╠═9cd7ccf0-a4e7-4445-a6b1-78ffa573eb3b
# ╠═4bcf1a8b-7101-41e9-bb30-9874275c20a6
# ╠═37a7d81a-ca8e-4ac5-b2ca-04b261beaddb
# ╠═01297be8-6234-4bae-91d5-963891b755ef
# ╠═9d7572dd-1ebe-426d-a8f9-3dd540775733
# ╠═aa3c48c6-3c83-47c3-ac59-ce12de38c371
# ╠═63496eae-e07f-4259-86a7-459de5025613
# ╠═8c10a242-7411-4973-9fdc-a5e8ce461ee4
# ╠═178e3c90-ed84-43e9-b7d8-2282c3758961
# ╠═2e1c70e9-6ecf-4e97-8705-6342028285aa
# ╠═a6e42cf4-1389-497f-90da-1df8297cec74
# ╠═759c3202-b6b7-45e7-ab11-75ed778273f7
# ╠═f398f371-5271-4af7-965b-73a7027eff0b
# ╠═00910312-2f5c-49bf-abda-11a6acf86249
# ╠═f7b87c23-dee5-462d-b4b9-b964947b9ca7
# ╠═131e6669-5a26-4d9c-9ef4-911aa779a20e
# ╠═18d8eaa0-5467-4123-bfc8-f52f377e7c72
# ╠═ac45ca81-79bc-4631-bf37-c08bbbf6159e
# ╠═cf3042b0-d5f3-4716-ab25-6ca736b491db
# ╠═794ac8f8-3eee-4a35-96b0-b5dca3615a07
# ╠═e571208c-50dd-487d-acb5-e17d5785f92b
# ╠═6ea54a0d-8b35-47d9-ac29-43b8f1d103db
# ╠═e7ab75e6-33b7-4429-b9a2-b8600856a6fc
# ╠═04bc7077-564a-470f-8138-c0ecf85d689f
# ╠═3a233b40-4e22-4a1b-9be5-c0990fc924bd
# ╠═dafbd900-6a41-49bc-8afe-e9e31022ab49
# ╠═54497681-00c7-4940-9047-23cf1d86b236
# ╠═50076b02-bd2c-4478-961b-9abee43d82ca
# ╠═c546afb2-f5cd-4290-ae6d-2805daa2a3fa
# ╠═4c76b220-b46a-4ba2-88f0-3bb787b802c2
# ╠═6a750201-47f6-4fcc-a551-7884c0280bc5
# ╠═56917df0-2e21-44c4-a7b7-3619a8661ab5
# ╠═ffb9d0d1-bca6-4b9a-87a7-e8c6280488fa
# ╠═4eeabfad-fb46-4d90-a586-aaf712c9eb47
# ╠═0397d23d-6c74-484b-9c8a-3989bab21239
# ╠═d7729d46-79ac-48c2-948a-41c91f78e2e3
# ╠═ac25b86e-97b3-4d54-b71a-a68a79a90995
# ╠═6ec7bab6-27c1-450d-a346-9abe523f1ca7
# ╠═75547508-ba93-4df5-af81-6026f88499a5
# ╠═2f87d310-8d44-4649-9dfb-440e160a24f4
# ╠═93f37121-c331-4e84-80ac-66c4c6e2aef6
# ╠═10a4a567-6337-418b-a70e-97647af0177b
# ╠═f333b7c7-bebb-47da-bbfc-b350f0f34a0d
# ╠═d995912c-5e3d-46da-a19b-730498af7ff5
# ╠═f35f3201-6180-418d-aa4a-b495f4a9de09
# ╠═64fa7f0f-5515-4990-839b-e92d5edf4f44
# ╠═9240273d-a92e-403e-a582-a7cb4789be60
# ╠═48577121-4f6b-494f-8ae4-d8db338089fa
# ╠═2837e158-e36c-49cd-9eaf-7ffd09f064b8
# ╠═d7648894-3e02-47ca-af42-a288190f699d
# ╠═c3fd5ca5-a8a4-4a38-a314-6d6ca7550784
# ╠═1201f9f7-1cff-4626-8ce4-cd07a830a35f
# ╠═cecc54f1-529b-456e-a3c4-1245f96f6102
# ╠═2c07fc77-c307-4e1c-89da-20b7e888ed93
# ╠═e31d09c9-692c-4e42-aaad-740bb1dd8046
# ╠═56132a5d-d190-488d-91fd-3a219e955715
# ╠═d3058953-4c3e-4d0d-b1fc-9c681cdcc817
# ╠═3af762e0-6920-4ff6-9c46-06512300c051
# ╠═83a0689f-1639-4f16-94cc-dc22df2aaf9f
# ╠═611a4da8-f77e-4ece-9509-25622e1e78b5
# ╠═a7ec3901-5982-4911-b7b4-30870e891b5c
# ╠═2d2ba724-3073-41aa-aab1-89e74e02e4f0
# ╠═da77f748-0896-43a5-8fb0-93d3cc887bd1
# ╠═5520c3fe-04e7-4028-a21e-4e5d3cbd4a11
# ╠═d86d7f62-100d-45f1-a71e-45ed79f97afb
# ╠═b86272a2-0675-4727-a002-4749e82a15b5
# ╠═c65dadd6-5587-4c8a-930e-cd2bf9b25604
# ╠═0631ecea-6fd8-44d9-9f5b-7a885126fca2
# ╠═1366db75-3e89-4d71-a398-b4d06005a1bd
# ╠═508f5350-f539-44a3-8b6a-94793083e6b7
# ╠═f15ad4b6-873a-4ce3-8321-5a38e9704df2
# ╠═ffc1b36a-7df4-48f6-8fff-5095d50d6039
# ╠═d0f9e26b-2a3c-42a4-a826-7c8694f5d470
# ╠═beb867b5-711f-47ba-b6d1-c3a6e63dd6f1
# ╠═33efdcc5-cc1d-48f4-81af-b5f65bb348f7
# ╠═6fc13d23-cb44-40a6-a52d-32b81855d6a0
# ╠═2d4732eb-47b0-498b-b0ff-c9dcf3951ecd
# ╠═769f772d-2695-468f-93a0-7655b5d08f10
# ╠═4bb62775-b172-4537-9087-c37cf9ea97f4
# ╠═46d3b837-c9df-4e04-98ae-611054c9ad6d
# ╠═a4d68f10-b2f3-4b48-b3d0-2baac6f93ca1
# ╠═bbc7767d-2ab4-40ff-ad2a-e1f81b6ad368
